### ISSUE TITLE
Error when calculating average

### ISSUE THREAD

**Issue by Hagellach37** [GIScience/hot-tm-critical-numbers#6]
This just happened to me,

I requested the average for British Red cross, when I got an internal Server error (500) When requesting the average for American Red Cross I got 502. However, when just requesting all projects for BRC or ARC everything works.

the process errored in pm2 and for a short time I got a 502 Bad Gateway, but then when sending the next request, everything worked. Still it says errored in pm2.

Maybe we need to think about how to avoid this. And maybe pm2 is not the perfect solution for our tool.

Happy to discuss on monday.

**Comment by Matthias-Schaub** [comment]
Those are two issues.

The first was caused by assigning projectIds as x_labels in the bar chart, but when calculating the mean there are but one bar in the chart. Current solution is to have no x_labels, when calculating the mean.

Second issue arises because pm2 only calls a bash script to start the application. From there on pm2 has no more controll of the application.

**Comment by Matthias-Schaub** [comment]
pm2 is not used anymore.
